##### **Make sure to be in the conda environment**

In [1]:
import sys
print(sys.executable)

D:\Anaconda\envs\steam_games_analysis\python.exe

#### 1. Data Cleaning
##### **Objective:** Load, explore and clean the datasets from Steam games and reviews 
##### to create a clean dataset and begin the exploratory analysis

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None) #To see all the columns for a better EDA

In [3]:
games = pd.read_csv('../data/raw/games.csv', 
                    encoding='utf-8', # in case theres special characters 
                    quotechar='"', # in case there's ',' in between '"' treat it like one cell
                    on_bad_lines='skip', # ignore instead of breaking 
                    index_col=False) # to prevent AppID being used as the default index

reviews = pd.read_csv('../data/raw/dataset.csv',
                      encoding='utf-8',
                      quotechar='"',
                      on_bad_lines='skip',
                      nrows=500_000, #Limit the rows so it doesnt take forever to read
                      index_col=False) 

print(f'Games: {games.shape}')
print(f'Reviews: {reviews.shape}')

Games: (122611, 39)
Reviews: (500000, 5)

#### **Explore both datasets**

##### **Explore the games dataset**

In [4]:
games.head(5)

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,Full audio languages,Reviews,Header image,Website,Support url,Support email,Windows,Mac,Linux,Metacritic score,Metacritic url,User score,Positive,Negative,Score rank,Achievements,Recommendations,Notes,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],[],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,NaN,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],[],NaN,https://shared.akamai.steamstatic.com/store_it...,http://mangagamer.org/supipara,http://mangagamer.com,support@mangagamer.com,True,False,False,0,NaN,0,252,3,NaN,0,231,NaN,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",[],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.facebook.com/8FloorGames/,https://www.facebook.com/8FloorGames,support@8floor.net,True,True,False,0,NaN,0,21,3,NaN,0,0,NaN,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],['Korean'],NaN,https://shared.akamai.steamstatic.com/store_it...,NaN,NaN,yujingamesc@gmail.com,True,False,False,0,NaN,0,0,0,NaN,19,0,The game includes the following elements. 1. G...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],['English'],NaN,https://shared.akamai.steamstatic.com/store_it...,https://www.realityexpanded.com/books-games,https://www.realityexpanded.com,support@realityexpanded.com,True,False,False,0,NaN,0,0,0,NaN,0,0,NaN,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...

In [5]:
games.info()

<class 'pandas.DataFrame'>
RangeIndex: 122611 entries, 0 to 122610
Data columns (total 39 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       122611 non-null  int64
 1   Name                        122610 non-null  str
 2   Release date                122611 non-null  str
 3   Estimated owners            122611 non-null  str
 4   Peak CCU                    122611 non-null  int64
 5   Required age                122611 non-null  int64
 6   Price                       122611 non-null  float64
 7   DiscountDLC count           122611 non-null  int64
 8   About the game              122611 non-null  int64
 9   Supported languages         114162 non-null  str
 10  Full audio languages        122611 non-null  str
 11  Reviews                     122611 non-null  str
 12  Header image                12070 non-null   str
 13  Website                     122530 non-null  str
 14  Support url                 49676 non-null   str
 15  Support email               54142 non-null   str
 16  Windows                     100348 non-null  str
 17  Mac                         122611 non-null  bool
 18  Linux                       122611 non-null  bool
 19  Metacritic score            122611 non-null  bool
 20  Metacritic url              122611 non-null  int64
 21  User score                  4256 non-null    str
 22  Positive                    122611 non-null  int64
 23  Negative                    122611 non-null  int64
 24  Score rank                  122611 non-null  int64
 25  Achievements                40 non-null      float64
 26  Recommendations             122611 non-null  int64
 27  Notes                       122611 non-null  int64
 28  Average playtime forever    22458 non-null   str
 29  Average playtime two weeks  122611 non-null  int64
 30  Median playtime forever     122611 non-null  int64
 31  Median playtime two weeks   122611 non-null  int64
 32  Developers                  122611 non-null  int64
 33  Publishers                  114174 non-null  str
 34  Categories                  113702 non-null  str
 35  Genres                      113658 non-null  str
 36  Tags                        114198 non-null  str
 37  Screenshots                 83346 non-null   str
 38  Movies                      116593 non-null  str
dtypes: bool(3), float64(2), int64(15), str(19)
memory usage: 34.0 MB

In [6]:
games.describe()

,AppID,Peak CCU,Required age,Price,DiscountDLC count,About the game,Metacritic url,Positive,Negative,Score rank,Achievements,Recommendations,Notes,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers
count,1.226110e+05,1.226110e+05,122611.000000,122611.000000,122611.000000,122611.000000,122611.000000,122611.000000,1.226110e+05,1.226110e+05,40.000000,122611.000000,1.226110e+05,1.226110e+05,122611.000000,1.226110e+05,122611.000000
mean,1.985386e+06,5.459332e+01,0.167611,4.765091,18.353663,0.545856,2.564941,0.024549,1.044986e+03,1.691974e+02,99.175000,18.087015,9.618250e+02,2.080232e+02,13.789268,1.735705e+02,14.722170
std,1.087595e+06,3.729452e+03,1.653591,12.531030,28.858970,14.516026,13.660559,1.394901,2.809173e+04,5.374645e+03,0.675107,141.493879,2.187880e+04,1.121768e+04,270.378053,1.120254e+04,294.509615
min,1.000000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,98.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000
25%,1.063175e+06,0.000000e+00,0.000000,0.550000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,99.000000,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000
50%,1.907380e+06,0.000000e+00,0.000000,2.240000,0.000000,0.000000,0.000000,0.000000,5.000000e+00,1.000000e+00,99.000000,2.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000
75%,2.869560e+06,0.000000e+00,0.000000,5.240000,40.000000,0.000000,0.000000,0.000000,3.700000e+01,1.000000e+01,100.000000,19.000000,0.000000e+00,0.000000e+00,0.000000,0.000000e+00,0.000000
max,4.264350e+06,1.013936e+06,21.000000,999.980000,100.000000,3703.000000,97.000000,100.000000,7.642084e+06,1.173003e+06,100.000000,9821.000000,4.830455e+06,3.429544e+06,20088.000000,3.429544e+06,20088.000000

In [7]:
print('Nulls per column in games:')
print(games.isnull().sum())

Nulls per column in games:
AppID                              0
Name                               1
Release date                       0
Estimated owners                   0
Peak CCU                           0
Required age                       0
Price                              0
DiscountDLC count                  0
About the game                     0
Supported languages             8449
Full audio languages               0
Reviews                            0
Header image                  110541
Website                           81
Support url                    72935
Support email                  68469
Windows                        22263
Mac                                0
Linux                              0
Metacritic score                   0
Metacritic url                     0
User score                    118355
Positive                           0
Negative                           0
Score rank                         0
Achievements                  122571
Recommendations                    0
Notes                              0
Average playtime forever      100153
Average playtime two weeks         0
Median playtime forever            0
Median playtime two weeks          0
Developers                         0
Publishers                      8437
Categories                      8909
Genres                          8953
Tags                            8413
Screenshots                    39265
Movies                          6018
dtype: int64

##### **Explore the reviews dataset**

In [8]:
reviews.head()

,app_id,app_name,review_text,review_score,review_votes
0,10,Counter-Strike,Ruined my life.,1,0
1,10,Counter-Strike,This will be more of a ''my experience with th...,1,1
2,10,Counter-Strike,This game saved my virginity.,1,0
3,10,Counter-Strike,• Do you like original games? • Do you like ga...,1,0
4,10,Counter-Strike,"Easy to learn, hard to master.",1,1

In [9]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   app_id        500000 non-null  int64
 1   app_name      485494 non-null  str
 2   review_text   499072 non-null  str
 3   review_score  500000 non-null  int64
 4   review_votes  500000 non-null  int64
dtypes: int64(3), str(2)
memory usage: 19.1 MB

In [10]:
reviews.describe()

              app_id   review_score   review_votes
count  500000.000000  500000.000000  500000.000000
mean    84887.385878       0.732724       0.100158
std     65907.007716       0.680527       0.300211
min        10.000000      -1.000000       0.000000
25%     13230.000000       1.000000       0.000000
50%    105600.000000       1.000000       0.000000
75%    110800.000000       1.000000       0.000000
max    202130.000000       1.000000       1.000000

In [11]:
print('Nulls per column in reviews:')
print(reviews.isnull().sum())

Nulls per column in reviews:
app_id              0
app_name        14506
review_text       928
review_score        0
review_votes        0
dtype: int64

In [12]:
reviews['app_id'].nunique()

332

#### **Time to clean the datasets**
- **Remove nulls from critical columns**
- **Change data types if necessary**
- **Rename columns if it has ambigous name**

#### **Starting with the games dataset**

In [13]:
games_clean = games.copy() 
drop_cols = [
    # > 95% nulls
    'Movies', 'Score rank', 'Reviews', 'Notes','Achievements','User score',
    # URLs don't really care
    'Header image', 'Screenshots', 'Metacritic url',
    # Contact Info
    'Website', 'Support url', 'Support email',
    # Too much text, not planning to use it 
    'About the game', 'Full audio languages',
]
games_clean.drop(columns=drop_cols, inplace=True)
print(f"Clean columns: {games_clean.shape[1]}")

Clean columns: 25

In [14]:
games_clean.dropna(subset =['AppID'], inplace=True)
games_clean['AppID'].isnull().sum()
duplicate = len(games_clean)

games_clean.drop_duplicates(subset = ['AppID'], keep = 'first', inplace = True)
print(f"Duplicates removed: {duplicate - len(games_clean)}")

games_clean.dropna(subset=['Name'], inplace=True)
games_clean['Name'].isnull().sum()

Duplicates removed: 0

np.int64(0)

In [15]:
games_clean['Release date'] = pd.to_datetime(
    games_clean['Release date'], format = '%b %d, %Y', errors = 'coerce')

print(f"Dates not parsed: {games_clean['Release date'].isna().sum()}")
games_clean['Release_year'] = games_clean['Release date'].dt.year
games_clean['Release_month'] = games_clean['Release date'].dt.month 
games_clean['Month_name'] = games_clean['Release date'].dt.month_name() # for dashboards

Dates not parsed: 0

In [16]:
owners = games_clean['Estimated owners'].str.replace(',', '', regex = False) #get both nums by replacing
split = owners.str.split(' - ', expand = True) # splitting them by '-', expand to separate in columns 

games_clean['Owners_mid'] = (split[0].astype(int) + split[1].astype(int)) // 2 # cast both as int and get the mean
games_clean.head(5)

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,Supported languages,Windows,Mac,Linux,Metacritic score,Positive,Negative,Recommendations,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Release_year,Release_month,Month_name,Owners_mid
0,2539430,Black Dragon Mage Playtest,2023-08-01,0 - 0,0,0,0.00,0,NaN,NaN,True,False,False,0,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,2023,8,August,0
1,496350,Supipara - Chapter 1 Spring Has Come!,2016-07-29,0 - 20000,0,0,5.24,65,"Springtime, April: when the cherry trees come ...",support@mangagamer.com,True,False,False,0,252,0,NaN,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,2016,7,July,10000
2,1034400,Mystery Solitaire The Black Raven,2019-05-06,0 - 20000,0,0,4.99,0,"Immerse yourself in the most beloved, mystical...",support@8floor.net,True,True,False,0,21,0,NaN,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,2019,5,May,10000
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,2024-10-31,0 - 20000,1,0,8.99,0,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",yujingamesc@gmail.com,True,False,False,0,0,19,The game includes the following elements. 1. G...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",2024,10,October,10000
4,3631080,Maze Quest VR,2025-04-24,0 - 20000,0,0,4.99,0,Its not just a Maze; its a Quest! Enter the ca...,support@realityexpanded.com,True,False,False,0,0,0,NaN,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",2025,4,April,10000

In [17]:
games_clean.drop(columns = ['Estimated owners'] , inplace = True) # drop old column, not needed anymore
games_clean.head(5)

,AppID,Name,Release date,Peak CCU,Required age,Price,DiscountDLC count,Supported languages,Windows,Mac,Linux,Metacritic score,Positive,Negative,Recommendations,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Release_year,Release_month,Month_name,Owners_mid
0,2539430,Black Dragon Mage Playtest,2023-08-01,0,0,0.00,0,NaN,NaN,True,False,False,0,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,2023,8,August,0
1,496350,Supipara - Chapter 1 Spring Has Come!,2016-07-29,0,0,5.24,65,"Springtime, April: when the cherry trees come ...",support@mangagamer.com,True,False,False,0,252,0,NaN,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,2016,7,July,10000
2,1034400,Mystery Solitaire The Black Raven,2019-05-06,0,0,4.99,0,"Immerse yourself in the most beloved, mystical...",support@8floor.net,True,True,False,0,21,0,NaN,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,2019,5,May,10000
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,2024-10-31,1,0,8.99,0,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",yujingamesc@gmail.com,True,False,False,0,0,19,The game includes the following elements. 1. G...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",2024,10,October,10000
4,3631080,Maze Quest VR,2025-04-24,0,0,4.99,0,Its not just a Maze; its a Quest! Enter the ca...,support@realityexpanded.com,True,False,False,0,0,0,NaN,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",2025,4,April,10000

In [18]:
text_cols = ['Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Supported languages']

for col in text_cols :
    flag_name = f"has_{col.lower().replace(' ','_')}"
    games_clean[flag_name] = games_clean[col].notna().astype(int)
    games_clean[col] = games_clean[col].fillna('')

games_clean.head(5)

,AppID,Name,Release date,Peak CCU,Required age,Price,DiscountDLC count,Supported languages,Windows,Mac,Linux,Metacritic score,Positive,Negative,Recommendations,Average playtime forever,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Release_year,Release_month,Month_name,Owners_mid,has_developers,has_publishers,has_categories,has_genres,has_tags,has_supported_languages
0,2539430,Black Dragon Mage Playtest,2023-08-01,0,0,0.00,0,,NaN,True,False,False,0,0,0,NaN,0,0,0,0,,,,,2023,8,August,0,1,0,0,0,0,0
1,496350,Supipara - Chapter 1 Spring Has Come!,2016-07-29,0,0,5.24,65,"Springtime, April: when the cherry trees come ...",support@mangagamer.com,True,False,False,0,252,0,NaN,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,2016,7,July,10000,1,1,1,1,1,1
2,1034400,Mystery Solitaire The Black Raven,2019-05-06,0,0,4.99,0,"Immerse yourself in the most beloved, mystical...",support@8floor.net,True,True,False,0,21,0,NaN,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,2019,5,May,10000,1,1,1,1,1,1
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,2024-10-31,1,0,8.99,0,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",yujingamesc@gmail.com,True,False,False,0,0,19,The game includes the following elements. 1. G...,0,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",2024,10,October,10000,1,1,1,1,1,1
4,3631080,Maze Quest VR,2025-04-24,0,0,4.99,0,Its not just a Maze; its a Quest! Enter the ca...,support@realityexpanded.com,True,False,False,0,0,0,NaN,0,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",2025,4,April,10000,1,1,1,1,1,1

In [19]:
games_clean[['Windows','Mac','Linux']] = games_clean[['Windows','Mac','Linux']].fillna(False) # fill NaN with false, we assume that its not supported

In [20]:
playtime_cols = ['Average playtime forever', 'Average playtime two weeks',
                 'Median playtime forever', 'Median playtime two weeks']
games_clean[playtime_cols] = games_clean[playtime_cols].fillna(0) # fill NaN with 0, since there's not enough data of playtime

In [21]:
games_clean.columns = ( # renaming all columns to have a standarized version
    games_clean.columns 
    .str.strip()
    .str.lower()
    .str.replace(' ','_')
)

print(f"\nFinal shape: {games_clean.shape}")
print(f"Nulls left:\n{games_clean.isnull().sum()[games_clean.isnull().sum() > 0]}")
games_clean.head(3)

Final shape: (122610, 34)
Nulls left:
Series([], dtype: int64)

,appid,name,release_date,peak_ccu,required_age,price,discountdlc_count,supported_languages,windows,mac,linux,metacritic_score,positive,negative,recommendations,average_playtime_forever,average_playtime_two_weeks,median_playtime_forever,median_playtime_two_weeks,developers,publishers,categories,genres,tags,release_year,release_month,month_name,owners_mid,has_developers,has_publishers,has_categories,has_genres,has_tags,has_supported_languages
0,2539430,Black Dragon Mage Playtest,2023-08-01,0,0,0.00,0,,False,True,False,False,0,0,0,0,0,0,0,0,,,,,2023,8,August,0,1,0,0,0,0,0
1,496350,Supipara - Chapter 1 Spring Has Come!,2016-07-29,0,0,5.24,65,"Springtime, April: when the cherry trees come ...",support@mangagamer.com,True,False,False,0,252,0,0,8,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,2016,7,July,10000,1,1,1,1,1,1
2,1034400,Mystery Solitaire The Black Raven,2019-05-06,0,0,4.99,0,"Immerse yourself in the most beloved, mystical...",support@8floor.net,True,True,False,0,21,0,0,0,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,2019,5,May,10000,1,1,1,1,1,1

In [23]:
games_clean.to_csv('../data/processed/games_clean.csv', index =False) # save the new and clean dataset to use later in the EDA
print('Saved') # print to make sure it's with no errors

Saved